# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false

# Mod identity
version=2.3.0-plus
mod_version=2.3.0-plus
group=com.github.woefulwolf
maven_group=com.github.woefulwolf
archives_base_name=terrain-diffusion-mc
java_version=21

mod_name=Terrain Diffusion+
mod_author=Woeful_Wolf
mod_id=terrain-diffusion-mc
fml_mod_id=terrain_diffusion_mc
license=MIT
credits=https://github.com/xandergos/terrain-diffusion-mc/
description=A fork of the original terrain generation mod by xandergos
mod_icon=assets/terrain-diffusion-mc/icon.png

# Minecraft / mappings
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.116.11+1.21.1
fabric_loader_version=0.18.1
loader_version=0.18.1


# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)
